#ifndef LOGDATACALIBRATE_GLOBAL_H
#define LOGDATACALIBRATE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGDATACALIBRATE_LIBRARY)
#  define LOGDATACALIBRATE_EXPORT Q_DECL_EXPORT
#else
#  define LOGDATACALIBRATE_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGDATACALIBRATE_GLOBAL_H
