#ifndef GEOMETROLOGYDB_GLOBAL_H
#define GEOMETROLOGYDB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GEOMETROLOGYDB_LIBRARY)
#  define GEOMETROLOGYDB_EXPORT Q_DECL_EXPORT
#else
#  define GEOMETROLOGYDB_EXPORT Q_DECL_IMPORT
#endif

#endif // GEOMETROLOGYDB_GLOBAL_H
